# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


shared: &shared
  rabbitmq:
      amqp_url: "amqp://ubuntu:ubuntu@192.168.0.11:5672"
      vhost: "test"
      cli_args: "-H 192.168.0.11 -u ubuntu -p ubuntu -V test"

development:
  secret_key_base: 631e46f88740c153eaba703a59d1976244c0266c155c8fe9cf534d03c75c7025c9fd3e72ec68e8a04a3625230fdd35df4b762c1c3f2493ddd4bda3372efb7d45
  <<: *shared

test:
  secret_key_base: 04f1f60819b1eb6d77bb9fd5e4bcbfa5bca4e3e70726090b91fc819a8ad60a9eb9e13cda108e94aa17f19531e6ba8f725f12ca31ec544eba2579932b0011cf4f
  <<: *shared

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *shared
